/// CORE_PROTOCOL message types.
/// See docs/CORE_PROTOCOL.md for the full specification.
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Orchestrator → Core (requests)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OrchestratorRequest {
    Spawn {
        id: String,
        subagent: String,
        input: serde_json::Value,
    },
    Approve {
        id: String,
        kind: ApproveKind,
        message: String,
        options: Vec<String>,
    },
    ConfigGet {
        id: String,
        key: String,
    },
    Complete {
        id: String,
        summary: String,
    },
    Blocked {
        id: String,
        message: String,
    },
    Notify {
        id: String,
        message: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        level: Option<NotifyLevel>,
    },
    CancelSpawn {
        id: String,
        spawn_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        grace_period_secs: Option<u64>,
    },
}

impl OrchestratorRequest {
    pub fn id(&self) -> &str {
        match self {
            Self::Spawn { id, .. } => id,
            Self::Approve { id, .. } => id,
            Self::ConfigGet { id, .. } => id,
            Self::Complete { id, .. } => id,
            Self::Blocked { id, .. } => id,
            Self::Notify { id, .. } => id,
            Self::CancelSpawn { id, .. } => id,
        }
    }

    /// Returns the exhaustive list of valid `type` values derived from this enum.
    /// Used to populate `session_start.config.protocol.request_types` so that the
    /// orchestrator always receives the authoritative list from core rather than
    /// relying on a separately maintained prompt.
    pub fn all_type_names() -> Vec<String> {
        vec![
            "spawn".to_string(),
            "approve".to_string(),
            "config_get".to_string(),
            "complete".to_string(),
            "blocked".to_string(),
            "notify".to_string(),
            "cancel_spawn".to_string(),
        ]
    }

    /// Returns the required fields for each request type.
    /// Used to populate `session_start.config.protocol.request_fields` so that
    /// the orchestrator has the authoritative field names without relying on the prompt.
    pub fn field_schema() -> std::collections::HashMap<String, Vec<String>> {
        [
            ("spawn", vec!["id", "subagent", "input"]),
            ("approve", vec!["id", "kind", "message", "options"]),
            ("config_get", vec!["id", "key"]),
            ("complete", vec!["id", "summary"]),
            ("blocked", vec!["id", "message"]),
            ("notify", vec!["id", "message"]),
            ("cancel_spawn", vec!["id", "spawn_id"]),
        ]
        .into_iter()
        .map(|(k, v)| (k.to_string(), v.into_iter().map(str::to_string).collect()))
        .collect()
    }

    /// Returns the authoritative protocol constraint rules injected into every `session_start`.
    /// These are generated by core and take precedence over any description in the system prompt.
    pub fn protocol_instructions() -> Vec<String> {
        vec![
            "Only send requests whose `type` value appears in `config.protocol.request_types`. \
             This list is generated by core and is exhaustive; any other `type` value will be ignored."
                .to_string(),
            "For each request type, include only the fields listed in \
             `config.protocol.request_fields[type]`. Do not use any other field names; \
             unrecognised fields cause the message to be dropped."
                .to_string(),
            "Only spawn subagents whose name appears in `config.subagents`. \
             Spawn requests for any other name are rejected with `unknown_subagent`."
                .to_string(),
        ]
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ApproveKind {
    Shell,
    Plan,
    Merge,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum NotifyLevel {
    Info,
    Warning,
    Error,
}

// ---------------------------------------------------------------------------
// Core → Orchestrator (responses and unsolicited events)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CoreMessage {
    SessionStart {
        id: String,
        prompt: String,
        recovery: bool,
        session_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        handover: Option<serde_json::Value>,
        config: SessionStartConfig,
    },
    SpawnAck {
        id: String,
    },
    SpawnResult {
        id: String,
        exit_code: i32,
        output: serde_json::Value,
        #[serde(skip_serializing_if = "Option::is_none")]
        truncated: Option<bool>,
    },
    SpawnError {
        id: String,
        reason: String,
    },
    ApproveResult {
        id: String,
        choice: String,
        decided_by: String,
    },
    ConfigResult {
        id: String,
        key: String,
        value: serde_json::Value,
    },
    BlockedResult {
        id: String,
        input: String,
    },
    CancelResult {
        id: String,
        spawn_id: String,
        status: CancelStatus,
    },
    Error {
        id: String,
        code: ErrorCode,
        message: String,
    },
    UserInput {
        id: String,
        text: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        metadata: Option<serde_json::Value>,
    },
    SessionAbort {
        id: String,
        reason: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionStartConfig {
    pub subagents: Vec<String>,
    pub max_spawns: u64,
    pub max_concurrent_spawns: u64,
    pub max_wall_time_secs: u64,
    pub protocol: ProtocolInfo,
}

/// Protocol metadata injected by core into every `session_start`.
/// The orchestrator must treat `request_types` as the definitive list of
/// valid `type` values it may send; no other values will be accepted.
/// `request_fields` maps each type to its required field names; the
/// orchestrator should use this as the authoritative field reference.
/// `instructions` contains the authoritative constraint rules the orchestrator
/// must follow; these are generated by core and take precedence over any
/// description in the system prompt.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProtocolInfo {
    /// Exhaustive list of valid `type` values the orchestrator may send to core.
    pub request_types: Vec<String>,
    /// Required fields for each request type (keyed by type name).
    pub request_fields: std::collections::HashMap<String, Vec<String>>,
    /// Authoritative constraint rules generated by core.
    pub instructions: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CancelStatus {
    Cancelled,
    AlreadyDone,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    UnknownSubagent,
    BudgetExceeded,
    SpawnLimitExceeded,
    UnknownSpawnId,
    InvalidRequest,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_spawn_round_trip() {
        let msg = OrchestratorRequest::Spawn {
            id: "req-001".to_string(),
            subagent: "coding-agent".to_string(),
            input: serde_json::json!({"prompt": "hello"}),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OrchestratorRequest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id(), "req-001");
    }

    #[test]
    fn test_approve_round_trip() {
        let msg = OrchestratorRequest::Approve {
            id: "req-002".to_string(),
            kind: ApproveKind::Merge,
            message: "Merge task/001?".to_string(),
            options: vec!["yes".to_string(), "no".to_string()],
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OrchestratorRequest = serde_json::from_str(&json).unwrap();
        if let OrchestratorRequest::Approve { kind, options, .. } = parsed {
            assert_eq!(kind, ApproveKind::Merge);
            assert_eq!(options.len(), 2);
        } else {
            panic!("wrong variant");
        }
    }

    #[test]
    fn test_core_message_session_start() {
        let msg = CoreMessage::SessionStart {
            id: "init-000".to_string(),
            prompt: "build a thing".to_string(),
            recovery: false,
            session_id: "sess-abc123".to_string(),
            handover: None,
            config: SessionStartConfig {
                subagents: vec!["orchestrator".to_string()],
                max_spawns: 0,
                max_concurrent_spawns: 0,
                max_wall_time_secs: 0,
                protocol: ProtocolInfo {
                    request_types: OrchestratorRequest::all_type_names(),
                    request_fields: OrchestratorRequest::field_schema(),
                    instructions: OrchestratorRequest::protocol_instructions(),
                },
            },
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"type\":\"session_start\""));
        assert!(json.contains("\"recovery\":false"));
        assert!(json.contains("\"request_types\""));
        assert!(json.contains("\"spawn\""));
    }

    #[test]
    fn test_error_code_serialization() {
        let msg = CoreMessage::Error {
            id: "req-001".to_string(),
            code: ErrorCode::UnknownSubagent,
            message: "subagent 'foo' is not defined".to_string(),
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("unknown_subagent"));
    }

    #[test]
    fn test_notify_level_optional() {
        let msg = OrchestratorRequest::Notify {
            id: "req-008".to_string(),
            message: "hello".to_string(),
            level: None,
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("\"level\""));
    }

    #[test]
    fn test_spawn_result_truncated_omitted_when_false() {
        let msg = CoreMessage::SpawnResult {
            id: "req-001".to_string(),
            exit_code: 0,
            output: serde_json::json!({"status": "success"}),
            truncated: None,
        };
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("truncated"));
    }
}
